# Generated by Django 4.2a1 on 2023-02-23 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0006_remove_duelplayer_duel_remove_duelquestion_duel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'wrong_answers_count',
                    models.IntegerField(
                        default=0, verbose_name='количество неправильных ответов'
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='duel',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='владец игры',
                    ),
                ),
            ],
            options={
                'verbose_name': 'дуэль',
                'verbose_name_plural': 'дуэли',
            },
        ),
        migrations.CreateModel(
            name='DuelQuestion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_answered', models.BooleanField(verbose_name='дан ответ')),
                (
                    'duel',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='questions',
                        to='duel.duel',
                        verbose_name='дуэль',
                    ),
                ),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='duel',
                        to='interview.question',
                        verbose_name='вопрос',
                    ),
                ),
            ],
            options={
                'verbose_name': 'вопрос в дуэли',
                'verbose_name_plural': 'вопросы в дуэли',
            },
        ),
        migrations.CreateModel(
            name='DuelPlayer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        default='Игрок', max_length=100, verbose_name='имя игрока'
                    ),
                ),
                (
                    'good_answers_count',
                    models.IntegerField(default=0, verbose_name='счетчик'),
                ),
                (
                    'duel',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='players',
                        to='duel.duel',
                        verbose_name='дуэль',
                    ),
                ),
            ],
            options={
                'verbose_name': 'участник дуэли',
                'verbose_name_plural': 'участники дуэли',
            },
        ),
    ]
