# Generated by Django 4.2a1 on 2023-02-24 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='owner',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='duel',
                to=settings.AUTH_USER_MODEL,
                verbose_name='владец игры',
            ),
            preserve_default=False,
        ),
    ]
