# Generated by Django 4.2a1 on 2023-11-08 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duel', '0003_alter_duelplayer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='duel',
                to=settings.AUTH_USER_MODEL,
                verbose_name='владелец игры',
            ),
        ),
    ]
