# Generated by Django 4.2a1 on 2023-02-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interview', '0002_duel_duelquestion_duelplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelplayer',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='счетчик'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(verbose_name='правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='текст вопроса'),
        ),
    ]
