# Generated by Django 4.2a1 on 2023-02-23 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0003_alter_duelplayer_counter_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='wrong_answers',
        ),
        migrations.AddField(
            model_name='duel',
            name='wrong_answers_count',
            field=models.IntegerField(
                default=0, verbose_name='количество неправильных ответов'
            ),
        ),
        migrations.AlterField(
            model_name='duel',
            name='owner',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='duels',
                to=settings.AUTH_USER_MODEL,
                verbose_name='владец игры',
            ),
        ),
    ]
