# Generated by Django 4.2a1 on 2023-02-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            'interview',
            '0004_remove_duel_wrong_answers_duel_wrong_answers_count_and_more',
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name='duelplayer',
            old_name='counter',
            new_name='good_answers_count',
        ),
        migrations.AlterField(
            model_name='duelplayer',
            name='duel',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='players',
                to='interview.duel',
                verbose_name='дуэль',
            ),
        ),
    ]
