# Generated by Django 4.2a1 on 2023-02-23 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('interview', '0005_rename_counter_duelplayer_good_answers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duelplayer',
            name='duel',
        ),
        migrations.RemoveField(
            model_name='duelquestion',
            name='duel',
        ),
        migrations.RemoveField(
            model_name='duelquestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='Duel',
        ),
        migrations.DeleteModel(
            name='DuelPlayer',
        ),
        migrations.DeleteModel(
            name='DuelQuestion',
        ),
    ]
