# Generated by Django 4.2a1 on 2023-02-24 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0006_remove_duelplayer_duel_remove_duelquestion_duel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='interviews',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
            preserve_default=False,
        ),
    ]
