# Generated by Django 4.2a1 on 2023-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interview', '0009_category_icon_language_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(
                default='icons/python3_logo.jpg',
                help_text='иконка',
                upload_to='icons',
                verbose_name='иконка',
            ),
        ),
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.ImageField(
                default='icons/python3_logo.jpg',
                help_text='иконка',
                upload_to='icons',
                verbose_name='иконка',
            ),
        ),
    ]
