# Generated by Django 4.2a1 on 2023-05-15 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interview', '0010_alter_category_icon_alter_language_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(
                max_length=500,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name='правильный ответ',
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(
                max_length=500,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name='текст вопроса',
            ),
        ),
    ]
