# Generated by Django 4.2a1 on 2023-08-18 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0012_questionlastdateused_lastuserrefreshdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastuserrefreshdate',
            name='date',
            field=models.DateTimeField(
                auto_now=True, verbose_name='дата обновления'
            ),
        ),
        migrations.AlterField(
            model_name='lastuserrefreshdate',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='q_refresh_date',
                to=settings.AUTH_USER_MODEL,
                unique=True,
                verbose_name='обновление лимита',
            ),
        ),
    ]
