# Generated by Django 4.2a1 on 2023-08-18 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0012_questionlastdateused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlastdateused',
            name='time',
        ),
        migrations.AddField(
            model_name='questionlastdateused',
            name='date',
            field=models.DateField(
                default='2023-08-01', verbose_name='дата использования'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionlastdateused',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='q_last_date_used',
                to='interview.question',
                verbose_name='вопрос',
            ),
        ),
        migrations.AlterField(
            model_name='questionlastdateused',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='q_last_date_used',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
    ]
