# Generated by Django 4.2a1 on 2023-11-08 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interview', '0012_lastuserrefreshdate_questionlastdateused'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionlastdateused',
            options={
                'verbose_name': 'дата последнего использования вопроса',
                'verbose_name_plural': 'даты последних использований вопросов',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(
                max_length=500,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name='правильный ответ',
            ),
        ),
        migrations.AlterField(
            model_name='questionlastdateused',
            name='date',
            field=models.DateTimeField(
                auto_now=True, verbose_name='дата использования'
            ),
        ),
    ]
