# Generated by Django 4.2a1 on 2023-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interview', '0012_questionlastdateused_lastuserrefreshdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastuserrefreshdate',
            name='date',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='дата обновления'
            ),
        ),
        migrations.AlterField(
            model_name='questionlastdateused',
            name='date',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='дата использования'
            ),
        ),
    ]
