# Generated by Django 4.2a1 on 2023-11-09 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0013_alter_questionlastdateused_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='questions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='автор',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions',
                to='interview.language',
                verbose_name='язык',
            ),
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        max_length=500,
                        validators=[
                            django.core.validators.MinLengthValidator(2)
                        ],
                        verbose_name='ответ',
                    ),
                ),
                (
                    'is_correct',
                    models.BooleanField(verbose_name='правильный ответ'),
                ),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='answers',
                        to='interview.question',
                        verbose_name='вопрос',
                    ),
                ),
            ],
        ),
    ]
