# Generated by Django 4.2a1 on 2023-08-18 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0013_alter_lastuserrefreshdate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastuserrefreshdate',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='q_refresh_date',
                to=settings.AUTH_USER_MODEL,
                verbose_name='обновление лимита',
            ),
        ),
    ]
