# Generated by Django 4.2a1 on 2023-08-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interview', '0013_remove_questionlastdateused_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlastdateused',
            name='date',
            field=models.DateField(
                auto_now_add=True, verbose_name='дата использования'
            ),
        ),
    ]
