# Generated by Django 4.2a1 on 2023-08-18 05:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0014_alter_questionlastdateused_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionlastdateused',
            unique_together={('user', 'question')},
        ),
    ]
