# Generated by Django 4.2a1 on 2023-08-18 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('interview', '0015_alter_questionlastdateused_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionlastdateused',
            unique_together=set(),
        ),
    ]
