# Generated by Django 4.2a1 on 2023-08-18 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0016_alter_questionlastdateused_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUserRefreshDate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'date',
                    models.DateField(
                        auto_now_add=True, verbose_name='дата обновления'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='q_refresh_date',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='обновление лимита',
                    ),
                ),
            ],
        ),
    ]
