# Generated by Django 4.2a1 on 2023-03-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    # replaces = [
    #     ('add_question', '0001_initial'),
    #     ('add_question', '0002_alter_addquestion_ip_address'),
    #     ('add_question', '0003_alter_addquestion_language'),
    #     ('add_question', '0004_addquestion_approved'),
    #     (
    #         'add_question',
    #         '0005_remove_addquestion_approved_addquestion_rejected',
    #     ),
    #     (
    #         'add_question',
    #         '0006_remove_addquestion_rejected_addquestion_status',
    #     ),
    #     ('add_question', '0007_alter_addquestion_status'),
    # ]

    initial = True

    dependencies = [
        ('interview', '0007_alter_interview_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuestion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('answer', models.TextField(verbose_name='правильный ответ')),
                (
                    'ip_address',
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name='IP-адрес'
                    ),
                ),
                (
                    'pub_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата публикации'
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='add_questions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='автор',
                    ),
                ),
                (
                    'language',
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='add_questions',
                        to='interview.language',
                        verbose_name='язык',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('proposed', 'Предложенный'),
                            ('rejected', 'Отклоненный'),
                            ('approved', 'Одобренный'),
                        ],
                        default='proposed',
                        max_length=10,
                        verbose_name='статус',
                    ),
                ),
            ],
            options={
                'verbose_name': 'предложенный вопрос',
                'verbose_name_plural': 'предложенные вопросы',
            },
        ),
    ]
