# Generated by Django 4.2a1 on 2023-03-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('add_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestion',
            name='ip_address',
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name='IP-адрес'
            ),
        ),
    ]
