# Generated by Django 4.2a1 on 2023-03-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('interview', '0007_alter_interview_user'),
        ('add_question', '0002_alter_addquestion_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestion',
            name='language',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='add_questions',
                to='interview.language',
                verbose_name='язык',
            ),
        ),
    ]
