# Generated by Django 4.2a1 on 2023-03-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('add_question', '0003_alter_addquestion_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='addquestion',
            name='approved',
            field=models.BooleanField(
                default=False, null=True, verbose_name='одобрено'
            ),
        ),
    ]
