# Generated by Django 4.2a1 on 2023-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('add_question', '0004_addquestion_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addquestion',
            name='approved',
        ),
        migrations.AddField(
            model_name='addquestion',
            name='rejected',
            field=models.BooleanField(
                default=False, null=True, verbose_name='отклонено'
            ),
        ),
    ]
