# Generated by Django 4.2a1 on 2023-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('add_question', '0005_remove_addquestion_approved_addquestion_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addquestion',
            name='rejected',
        ),
        migrations.AddField(
            model_name='addquestion',
            name='status',
            field=models.CharField(
                choices=[
                    ('P', 'Предложенный'),
                    ('R', 'Отклоненный'),
                    ('A', 'Одобренный'),
                ],
                default='P',
                max_length=1,
                verbose_name='статус',
            ),
        ),
    ]
