# Generated by Django 4.2a1 on 2023-03-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('add_question', '0006_remove_addquestion_rejected_addquestion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestion',
            name='status',
            field=models.CharField(
                choices=[
                    ('proposed', 'Предложенный'),
                    ('rejected', 'Отклоненный'),
                    ('approved', 'Одобренный'),
                ],
                default='proposed',
                max_length=10,
                verbose_name='статус',
            ),
        ),
    ]
