# Generated by Django 4.2a1 on 2023-05-15 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('add_question', '0008_addquestion_user_cookie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addquestion',
            old_name='user_cookie',
            new_name='user_cookie_id',
        ),
        migrations.AlterField(
            model_name='addquestion',
            name='answer',
            field=models.TextField(
                max_length=500,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name='правильный ответ',
            ),
        ),
        migrations.AlterField(
            model_name='addquestion',
            name='text',
            field=models.TextField(
                max_length=500,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name='текст вопроса',
            ),
        ),
    ]
