# Generated by Django 4.2a1 on 2023-11-09 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('add_question', '0010_remove_addquestion_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestion',
            name='answer',
            field=models.TextField(
                max_length=500,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name='ответ',
            ),
        ),
    ]
