# Generated by Django 4.2a1 on 2023-03-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('addquestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addquestion',
            name='ip_address',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='IP-адрес'
            ),
        ),
        migrations.AddField(
            model_name='addquestion',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name='Дата публикации'
            ),
        ),
    ]
