# Generated by Django 4.2a1 on 2023-07-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencekey',
            name='value',
            field=models.UUIDField(unique=True, verbose_name='значение'),
        ),
    ]
