# Generated by Django 4.2a1 on 2023-02-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254, unique=True, verbose_name='электронная почта'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_duel_moderator',
            field=models.BooleanField(
                default=False, verbose_name='признак модератора для дуэлей'
            ),
        ),
    ]
