# Generated by Django 3.2.18 on 2023-02-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_duel_moderator',
            field=models.BooleanField(default=False, verbose_name='признак модератора для дуэлей'),
        ),
    ]
