# Generated by Django 4.2a1 on 2023-04-28 13:55

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'Имя пользователя занято'},
                help_text='Обязательное поле. От 2 до 25 символов. Буквы, цифры, @/./+/-/_ допускаются.',
                max_length=25,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name='имя пользователя',
            ),
        ),
    ]
