# Generated by Django 4.2a1 on 2023-04-26 12:33

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={
                    'unique': 'A user with that username already exists.'
                },
                help_text='Required. 25 characters or fewer. Letters, digits and @/./+/-/_ only.',
                max_length=25,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator()
                ],
                verbose_name='username',
            ),
        ),
    ]
