# Generated by Django 4.2a1 on 2023-05-11 09:53

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'Имя пользователя занято'},
                help_text='Обязательное поле. От 2 до 25 символов. Буквы, цифры, @/./+/-/_ допускаются.',
                max_length=25,
                unique=True,
                validators=[
                    users.validators.CustomUsernameValidator(),
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name='имя пользователя',
            ),
        ),
    ]
