name: PR_CLOSED DEPLOY AND TG ALERT

on:
  pull_request:
    types: [closed]
    branches:
    - test


jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jinglemybells/hire:test_latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/test
            sudo docker-compose stop backend_test
            sudo docker-compose pull
            sudo docker-compose up -d

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        if: github.event.pull_request.merged == true
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHANNEL }}
          token: ${{ secrets.BOT }}
          message: ${{ github.event_name }} ветки ${{ github.head_ref }} успешно смержен в ${{ github.base_ref }}, тестовый сервер обновлен и перезапущен
      - name: send message merged
        if: github.event.pull_request.merged == false
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHANNEL }}
          token: ${{ secrets.BOT }}
          message: ${{ github.event_name }} ветки ${{ github.head_ref }} в ${{ github.base_ref }} закрыт без мержа, деплой не производился.
